<h3>Taxonomias</h3>


<? if (count($this->paginator)): ?>
<table class="listclass" width="100%" border="0" cellpadding="0" cellspacing="0">
    <thead>
      <tr>
            <th width="10%" align="left">ID</th>
            <th width="10%" align="left">Titulo</th>
            <th width="10%" align="left"></th>
      </tr>
    </thead>

    <tbody>
        <? $i=0; foreach ($this->paginator as $taxonomy) :  ?>
              <tr class=<?php echo ($i%2==0?'"even"':'"odd"') ?>>
                    <td valign="top"><?php echo $taxonomy['taxonomy_id']; ?></td>
                    <td valign="top"><?php echo $taxonomy['title'] ?></td>
                    <td valign="top">
						<?php echo $this->href( "taxonomy", "update", "editar termino", array( "tid" => $taxonomy['taxonomy_id'], 'vid' => $this->vid ) ) ?>
                    </td>

              </tr>
        <? $i++; endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginator ?>
<? endif; ?>
<p>
<?php echo $this->href( "taxonomy", "create", "Crear un nuevo termino", array( 'vid' => $this->vid)  ) ?>
</p>

